language: python
matrix:
  include:
    - arch: arm64
      python: 3.8
    - arch: amd64
      python: 3.8
    - arch: arm64-graviton2
      group: edge
      virt: lxd
      dist: xenial
sudo: false
dist: xenial
install:
  - |
    # pip install
    pip install --upgrade setuptools pip
    pip install --pre --upgrade --upgrade-strategy=eager .[test] codecov
  - |
    # install matplotlib
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install matplotlib curio trio
    fi
  - |
    # pin tornado
    if [[ ! -z "$TORNADO" ]]; then
      pip install tornado=="$TORNADO"
    fi
  - |
    # pin IPython
    if [[ ! -z "$IPYTHON" ]]; then
      if [[ "$IPYTHON" == "master" ]]; then
        SPEC=git+https://github.com/ipython/ipython#egg=ipython
      else
        SPEC="ipython==$IPYTHON"
      fi
      pip install --upgrade --pre "$SPEC"
    fi
  - pip freeze
script:
  - jupyter kernelspec list
  - pytest --cov ipykernel --durations 10 -v ipykernel
after_success:
  - codecov
